<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>"Глубокое обучение". Продвинутый поток</b></h3>

<h2 style="text-align: center;"><b>Семинар 6. Основы библиотеки Pythorch </b></h2>


<h2 style="text-align: center;"><b>PyTorch basics: syntax, torch.cuda and torch.autograd</b></h2>

<p style="align: center;"><img src="https://upload.wikimedia.org/wikipedia/commons/9/96/Pytorch_logo.png" width=400 height=100></p>

Hi! In this notebook we will cover the basics of the **PyTorch deep learning framework**. 

<h3 style="text-align: center;"><b>Intro</b></h3>

**Frameworks** are the specific code libraries with their own internal structure and pipelines.

There are many deep learning frameworks nowadays (02/2019). The difference between them is in the internal computation principles. For example, in **[Caffe](http://caffe.berkeleyvision.org/)** and **[Caffe2](https://caffe2.ai/)** you write the code using some "ready blocks" (just like the $LEGO^{TM}$ :). In **[TensorFlow](https://www.tensorflow.org/)** and **[Theano](http://deeplearning.net/software/theano/)** you declare the computation graph at first, then compile it and use it for inference/training (`tf.session()`). By the way, now TensorFlow (since v1.10) has the [Eager Execution](https://www.tensorflow.org/guide/eager), which can be handy for fast prototyping and debugging. **[Keras](https://keras.io/)** is a very popular and useful DL framework that allows to create networks fast and has many demanding features. 

<p style="align: center;"><img src="https://habrastorage.org/web/e3e/c3e/b78/e3ec3eb78d714a7993a6b922911c0866.png" width=500 height=500></p>  
<p style="text-align: center;"><i>Image credit: https://habr.com/post/334380/</i><p>

We will use PyTorch bacause it's been actively developed and supported by the community and [Facebook AI Research](https://research.fb.com/category/facebook-ai-research/).

<h3 style="text-align: center;"><b>Installation</b></h3>

The detailed instruction on how to install PyTorch you can find on the [official PyTorch website](https://pytorch.org/).

<h3 style="text-align: center;">Syntax<b></b></h3>

In [1]:
import torch

Some facts about PyTorch:  
- dynamic computation graph
- handy `torch.nn` and `torchvision` modules for fast neural network prototyping
- even faster than TensorFlow on some tasks
- allows to use GPU easily

If PyTorch was a formula, it would be:  

$$PyTorch = NumPy + CUDA + Autograd$$

(CUDA - [wiki](https://en.wikipedia.org/wiki/CUDA))

Let's see how we can use PyTorch to operate with vectors and tensors.  

Recall that **a tensor** is a multidimensional vector, e.g. :  

`x = np.array([1,2,3])` -- a vector = a tensor with 1 dimension (to be more precise: `(1,)`)  
`y = np.array([[1, 2, 3], [4, 5, 6]])` -- a matrix = a tensor with 2 dimensions (`(2, 3)` in this case)  
`z = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],  
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]],  
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])` -- "a cube" (3, 3, 3) = a tensor with 3 dimensions (`(3, 3, 3)` in this case)

One real example of 3-dimensional tensor is **an image**, it has 3 dimensions: `height`, `width` and the `channel depth` (= 3 for color images, 1 for a greyscale). You can think of it as of parallelepiped consisting of the real numbers.

In PyTorch we will use `torch.Tensor` (`FloatTensor`, `IntTensor`, `ByteTensor`) for all the computations.

All tensor types:

In [2]:
torch.HalfTensor      # 16 бит, floating point
torch.FloatTensor     # 32 бита, floating point
torch.DoubleTensor    # 64 бита, floating point

torch.ShortTensor     # 16 бит, integer, signed
torch.IntTensor       # 32 бита, integer, signed
torch.LongTensor      # 64 бита, integer, signed

torch.CharTensor      # 8 бит, integer, signed
torch.ByteTensor      # 8 бит, integer, unsigned

torch.ByteTensor

We will use only `torch.FloatTensor()` and `torch.IntTensor()`. 

Let's begin to do something!

* Creating the tensor:

In [3]:
a = torch.FloatTensor([1, 2])
a

tensor([1., 2.])

In [4]:
a.shape

torch.Size([2])

In [5]:
b = torch.FloatTensor([[1,2,3], [4,5,6]])
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
b.shape

torch.Size([2, 3])

In [7]:
x = torch.FloatTensor(2,3,4)

In [8]:
x

tensor([[[8.9038e-36, 0.0000e+00, 7.0065e-44, 6.7262e-44],
         [6.3058e-44, 6.7262e-44, 7.7071e-44, 6.3058e-44],
         [6.7262e-44, 6.8664e-44, 1.1771e-43, 6.8664e-44]],

        [[6.8664e-44, 8.1275e-44, 7.2868e-44, 6.7262e-44],
         [8.1275e-44, 7.1466e-44, 7.1466e-44, 6.4460e-44],
         [6.8664e-44, 7.1466e-44, 6.8664e-44, 6.7262e-44]]])

In [9]:
x = torch.FloatTensor(100)
x

tensor([ 9.4185e-36,  0.0000e+00,  1.4396e-38,  0.0000e+00,  5.8154e-43,
         0.0000e+00,         nan,         nan,  4.4721e+21,  2.3079e+20,
         6.2689e+22,  4.7428e+30,  1.3563e-19,  1.3817e-19, -1.0752e+10,
        -9.9222e+10,  1.8910e+23,  7.1443e+31,  1.9603e-19,  1.8061e+28,
         7.5527e+28,  5.2839e-11,  2.7604e+20,  1.7744e+28,  2.0535e-19,
         1.3563e-19,  1.0426e-08, -2.3866e+10, -1.7558e+10,  1.8910e+23,
         7.1443e+31,  1.9603e-19,  1.8061e+28,  7.5527e+28,  5.2839e-11,
         1.1319e+21,  6.2688e+22,  4.7428e+30,  1.3563e-19,  1.6962e-07,
        -2.3866e+10, -1.7558e+10,  1.8910e+23,  7.1443e+31,  1.9603e-19,
         1.8061e+28,  4.3747e+31,  4.2964e+24,  7.1901e+28,  6.2706e+22,
         4.7428e+30,  1.3563e-19,  2.3303e-09, -6.0573e-09, -3.0816e-37,
         1.8037e+28,  6.8296e+22,  1.2690e+31,  7.0364e+22,  7.5527e+28,
         5.2839e-11,  4.1993e+12,  7.5338e+28,  1.3563e-19,  1.3563e-19,
         1.0426e-08, -2.3866e+10, -1.7558e+10,  1.2

In [10]:
x = torch.IntTensor(45, 57, 14, 2)
x.shape

torch.Size([45, 57, 14, 2])

**Note:** if you create `torch.Tensor` with the following constructor it will be filled with the "random trash numbers":

In [11]:
x = torch.IntTensor(3, 2, 4)
x

tensor([[[87907584,        0,       50,       48],
         [      45,       48,       55,       45]],

        [[      48,       49,       84,       49],
         [      49,       58,       52,       48]],

        [[      58,       51,       51,       46],
         [      49,       54,       51,       50]]], dtype=torch.int32)

Here is a way to fill a new tensor with zeroes:

In [12]:
x = torch.IntTensor(3, 2, 4).zero_()
x

tensor([[[0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0]]], dtype=torch.int32)

## Как писать на torch, если знаешь numpy

Все функции на numpy имеют соответствующие функции на torch. Их соответствие вы можете посмотреть здесь:

https://github.com/torch/torch7/wiki/Torch-for-Numpy-users

`np.reshape()` == `torch.view()`:

In [13]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [14]:
b.view(3, 2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

**Note:** `torch.view()` creates a new tensor, one the old one remains unchanged

In [15]:
b.view(-1)

tensor([1., 2., 3., 4., 5., 6.])

In [16]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

* Change a tensor type:

In [17]:
a = torch.FloatTensor([1.5, 3.2, -7])

In [18]:
a.type_as(torch.IntTensor())

tensor([ 1,  3, -7], dtype=torch.int32)

In [19]:
a.type_as(torch.ByteTensor())

tensor([  1,   3, 249], dtype=torch.uint8)

**Note:** `.type_as()` creates a new tensor, the old one remains unchanged

In [20]:
a

tensor([ 1.5000,  3.2000, -7.0000])

* Indexing is just like in `NumPy`:

In [21]:
a = torch.FloatTensor([[100, 20, 35], [15, 163, 534], [52, 90, 66]])
a

tensor([[100.,  20.,  35.],
        [ 15., 163., 534.],
        [ 52.,  90.,  66.]])

In [22]:
a[0, 0]

tensor(100.)

In [23]:
a[0][0]

tensor(100.)

In [24]:
a[0:2, 0:2]

tensor([[100.,  20.],
        [ 15., 163.]])

**Ariphmetics and boolean operations** and their analogues:  

| Оператор | Аналог |
|:-:|:-:|
|`+`| `torch.add()` |
|`-`| `torch.sub()` |
|`*`| `torch.mul()` |
|`/`| `torch.div()` |

* Addition:

In [25]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [26]:
a + b

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])

In [27]:
a.add(b)

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])

In [28]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [29]:
a + b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

* Subtraction:

In [30]:
a - b

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

In [31]:
a.sub(b)

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

* Multiplication (elementwise):

In [32]:
a * b

tensor([[-1.0000e+00, -4.0000e+00, -9.0000e+00],
        [-1.0000e+02, -4.0000e+02, -9.0000e+02],
        [-1.0000e+04, -4.0000e+04, -9.0000e+04]])

In [33]:
a.mul(b)

tensor([[-1.0000e+00, -4.0000e+00, -9.0000e+00],
        [-1.0000e+02, -4.0000e+02, -9.0000e+02],
        [-1.0000e+04, -4.0000e+04, -9.0000e+04]])

* Division (elementwise):

In [34]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [35]:
a / b

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

Лучше:

In [36]:
a.div(b)

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

**Note:** all this operations create new tensors, the old tensors remain unchanged

In [37]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [38]:
b

tensor([[ -1.,  -2.,  -3.],
        [-10., -20., -30.],
        [100., 200., 300.]])

* Comparison operators:

In [39]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [40]:
a == b

tensor([[False, False, False],
        [False, False, False],
        [ True,  True,  True]])

In [41]:
a != b

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False]])

In [42]:
a < b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [43]:
a > b

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False]])

* Using boolean mask indexing:

In [44]:
a[a > b]

tensor([ 1.,  2.,  3., 10., 20., 30.])

In [45]:
b[a == b]

tensor([100., 200., 300.])

Elementwise application of the **universal functions**:

In [46]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])

In [47]:
a.sin()

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [48]:
torch.sin(a)

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [49]:
a.cos()

tensor([[ 0.5403, -0.4161, -0.9900],
        [-0.8391,  0.4081,  0.1543],
        [ 0.8623,  0.4872, -0.0221]])

In [50]:
a.exp()

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01],
        [2.2026e+04, 4.8517e+08, 1.0686e+13],
        [       inf,        inf,        inf]])

In [51]:
a.log()

tensor([[0.0000, 0.6931, 1.0986],
        [2.3026, 2.9957, 3.4012],
        [4.6052, 5.2983, 5.7038]])

In [52]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [53]:
b.abs()

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

* The sum, mean, max, min:

In [54]:
a.sum()

tensor(666.)

In [55]:
a.mean()

tensor(74.)

Along axis:

In [56]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [57]:
a.sum(dim=0)

tensor([111., 222., 333.])

In [58]:
a.sum(1)

tensor([  6.,  60., 600.])

In [59]:
a.max()

tensor(300.)

In [60]:
a.max(0)

torch.return_types.max(values=tensor([100., 200., 300.]), indices=tensor([2, 2, 2]))

In [61]:
a.min()

tensor(1.)

In [62]:
a.min(0)

torch.return_types.min(values=tensor([1., 2., 3.]), indices=tensor([0, 0, 0]))

**Note:** the second tensor returned by `.max()` and `.min()` contains the indices of max/min elements along this axis. E.g. in that case `a.min()` returned `(1, 2, 3)` which are the minimum elements along 0 axis (along columns) and their indices along 0 axis are `(0, 0, 0)`.

**Matrix operations**:

* Transpose a tensor:

In [63]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [64]:
a.t()

tensor([[  1.,  10., 100.],
        [  2.,  20., 200.],
        [  3.,  30., 300.]])

It is not not the inplace operation too:

In [65]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

* Dot product of vectors:

In [66]:
a = torch.FloatTensor([1, 2, 3, 4, 5, 6])
b = torch.FloatTensor([-1, -2, -4, -6, -8, -10])

In [67]:
a.dot(b)

tensor(-141.)

In [68]:
a.shape, b.shape

(torch.Size([6]), torch.Size([6]))

In [69]:
a @ b

tensor(-141.)

In [70]:
type(a)

torch.Tensor

In [71]:
type(b)

torch.Tensor

In [72]:
type(a @ b)

torch.Tensor

* Matrix product:

In [73]:
a = torch.FloatTensor([[1, 2, 3],
                       [10, 20, 30],
                       [100, 200, 300]])

b = torch.FloatTensor([[-1, -2, -3],
                       [-10, -20, -30],
                       [100, 200, 300]])

In [74]:
a.mm(b)

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [75]:
a @ b

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

Remain unchanged:

In [76]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [77]:
b

tensor([[ -1.,  -2.,  -3.],
        [-10., -20., -30.],
        [100., 200., 300.]])

In [78]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1], [-10], [100]])

In [79]:
print(a.shape, b.shape)

torch.Size([3, 3]) torch.Size([3, 1])


In [80]:
a @ b

tensor([[  279.],
        [ 2790.],
        [27900.]])

If we unroll the tensor `b` in an array (`torch.view(-1)`) the multiplication would be like with the column:

In [81]:
b

tensor([[ -1.],
        [-10.],
        [100.]])

In [82]:
b.view(-1)

tensor([ -1., -10., 100.])

In [83]:
b.view(-1).shape

torch.Size([3])

In [84]:
a @ b.view(-1)

tensor([  279.,  2790., 27900.])

In [85]:
a.mv(b.view(-1))

tensor([  279.,  2790., 27900.])

**From NumPy to PyTorch conversion**:

In [86]:
import numpy as np

a = np.random.rand(3, 3)
a

array([[0.24456612, 0.40961029, 0.60712667],
       [0.29554393, 0.82733622, 0.66154989],
       [0.22808437, 0.51380553, 0.42993016]])

In [87]:
b = torch.from_numpy(a)
b

tensor([[0.2446, 0.4096, 0.6071],
        [0.2955, 0.8273, 0.6615],
        [0.2281, 0.5138, 0.4299]], dtype=torch.float64)

**NOTE!** `a` and `b` have the same data storage, so the changes in one tensor will lead to the changes in another:

In [88]:
b -= b
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [89]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**From PyTorch to NumPy conversion:**

In [90]:
a = torch.FloatTensor(2, 3, 4)
a

tensor([[[8.9042e-36, 0.0000e+00, 7.0065e-44, 6.7262e-44],
         [6.3058e-44, 6.7262e-44, 7.7071e-44, 6.3058e-44],
         [6.7262e-44, 6.8664e-44, 1.1771e-43, 6.8664e-44]],

        [[6.8664e-44, 8.1275e-44, 7.2868e-44, 6.7262e-44],
         [8.1275e-44, 7.1466e-44, 7.1466e-44, 6.4460e-44],
         [7.0065e-44, 7.1466e-44, 7.7071e-44, 7.5670e-44]]])

In [91]:
type(a)

torch.Tensor

In [92]:
x = a.numpy()
x

array([[[8.904186e-36, 0.000000e+00, 7.006492e-44, 6.726233e-44],
        [6.305843e-44, 6.726233e-44, 7.707142e-44, 6.305843e-44],
        [6.726233e-44, 6.866362e-44, 1.177091e-43, 6.866362e-44]],

       [[6.866362e-44, 8.127531e-44, 7.286752e-44, 6.726233e-44],
        [8.127531e-44, 7.146622e-44, 7.146622e-44, 6.445973e-44],
        [7.006492e-44, 7.146622e-44, 7.707142e-44, 7.567012e-44]]],
      dtype=float32)

In [93]:
x.shape

(2, 3, 4)

In [94]:
type(x)

numpy.ndarray

Let's write the `forward_pass(X, w)` ($w_0$ is a part of the $w$) for a single neuron (activation = sigmoid) using PyTorch:

In [95]:
def forward_pass(X, w):
    return torch.sigmoid(X @ w)

In [96]:
X = torch.FloatTensor([[-5, 5], [2, 3], [1, -1]])
w = torch.FloatTensor([[-0.5], [2.5]])
result = forward_pass(X, w)
print('result: {}'.format(result))

result: tensor([[1.0000],
        [0.9985],
        [0.0474]])


In [97]:
torch.sigmoid(torch.FloatTensor([10]))

tensor([1.0000])

<h3 style="text-align: center;"><a href="https://ru.wikipedia.org/wiki/CUDA">CUDA</a></h3>

In [98]:
torch.cuda.is_available()

True

In [99]:
torch.cuda.device

torch.cuda.device

In [100]:
torch.cuda.device_count()

1

In [101]:
torch.cuda.is_initialized()

False

[CUDA documentation](https://docs.nvidia.com/cuda/)

We can use both CPU (Central Processing Unit) and GPU (Graphical Processing Unit) to make the computations with PyTorch. We can switch between them easily, this is one of the most important things in PyTorch framework.

In [102]:
x = torch.FloatTensor(1024, 1024).uniform_()
x

tensor([[0.9303, 0.1521, 0.2655,  ..., 0.1569, 0.8508, 0.4907],
        [0.1881, 0.0548, 0.4797,  ..., 0.5322, 0.4339, 0.9817],
        [0.3699, 0.9628, 0.4378,  ..., 0.8400, 0.7011, 0.1518],
        ...,
        [0.7357, 0.0020, 0.1645,  ..., 0.6601, 0.1463, 0.3845],
        [0.8687, 0.1450, 0.5390,  ..., 0.4467, 0.7556, 0.9678],
        [0.5793, 0.8441, 0.4322,  ..., 0.8159, 0.6220, 0.4496]])

In [103]:
x.is_cuda

False

Place a tensor on GPU:

In [104]:
x = x.cuda()

In [105]:
x

tensor([[0.9303, 0.1521, 0.2655,  ..., 0.1569, 0.8508, 0.4907],
        [0.1881, 0.0548, 0.4797,  ..., 0.5322, 0.4339, 0.9817],
        [0.3699, 0.9628, 0.4378,  ..., 0.8400, 0.7011, 0.1518],
        ...,
        [0.7357, 0.0020, 0.1645,  ..., 0.6601, 0.1463, 0.3845],
        [0.8687, 0.1450, 0.5390,  ..., 0.4467, 0.7556, 0.9678],
        [0.5793, 0.8441, 0.4322,  ..., 0.8159, 0.6220, 0.4496]],
       device='cuda:0')

In [106]:
x.is_cuda

True

Let's multiply two tensors on GPU and then move the result on the CPU:

In [107]:
a = torch.FloatTensor(10000*2, 10000).uniform_()
b = torch.FloatTensor(10000*2, 10000).uniform_()

In [108]:
print('Check:')
print('a.device:', a.device)
print('b.device:', b.device)
print()

# element-wise multiplication
%time c = a.mul(b)
c

Check:
a.device: cpu
b.device: cpu

CPU times: user 141 ms, sys: 297 ms, total: 438 ms
Wall time: 438 ms


tensor([[0.1809, 0.2797, 0.2678,  ..., 0.1233, 0.0314, 0.0545],
        [0.1336, 0.0858, 0.2172,  ..., 0.3561, 0.0449, 0.1487],
        [0.0604, 0.0649, 0.5872,  ..., 0.0055, 0.3881, 0.0833],
        ...,
        [0.2063, 0.3222, 0.2788,  ..., 0.5650, 0.1698, 0.2132],
        [0.0053, 0.1174, 0.0619,  ..., 0.6467, 0.7006, 0.0561],
        [0.3516, 0.3521, 0.6811,  ..., 0.2228, 0.1606, 0.0200]])

In [109]:
ac = a.cuda()
bc = b.cuda()

In [110]:
print('Check:')
print('ac.device:', ac.device)
print('bc.device:', bc.device)
print()

%time c = ac.mul(bc)
c

Check:
ac.device: cuda:0
bc.device: cuda:0

CPU times: user 592 µs, sys: 2.19 ms, total: 2.78 ms
Wall time: 2.6 ms


tensor([[0.1809, 0.2797, 0.2678,  ..., 0.1233, 0.0314, 0.0545],
        [0.1336, 0.0858, 0.2172,  ..., 0.3561, 0.0449, 0.1487],
        [0.0604, 0.0649, 0.5872,  ..., 0.0055, 0.3881, 0.0833],
        ...,
        [0.2063, 0.3222, 0.2788,  ..., 0.5650, 0.1698, 0.2132],
        [0.0053, 0.1174, 0.0619,  ..., 0.6467, 0.7006, 0.0561],
        [0.3516, 0.3521, 0.6811,  ..., 0.2228, 0.1606, 0.0200]],
       device='cuda:0')

In [111]:
c.device

device(type='cuda', index=0)

In [112]:
print(c.device)

cuda:0


In [113]:
c.device.type

'cuda'

In [114]:
c.device.index

0

In [115]:
# get c back on CPU
c = a.cuda().mul(b.cuda()).cpu()

c

tensor([[0.1809, 0.2797, 0.2678,  ..., 0.1233, 0.0314, 0.0545],
        [0.1336, 0.0858, 0.2172,  ..., 0.3561, 0.0449, 0.1487],
        [0.0604, 0.0649, 0.5872,  ..., 0.0055, 0.3881, 0.0833],
        ...,
        [0.2063, 0.3222, 0.2788,  ..., 0.5650, 0.1698, 0.2132],
        [0.0053, 0.1174, 0.0619,  ..., 0.6467, 0.7006, 0.0561],
        [0.3516, 0.3521, 0.6811,  ..., 0.2228, 0.1606, 0.0200]])

In [116]:
a

tensor([[0.9663, 0.6150, 0.3112,  ..., 0.1679, 0.0858, 0.2368],
        [0.3382, 0.7518, 0.4138,  ..., 0.9250, 0.5041, 0.7196],
        [0.1306, 0.4290, 0.7299,  ..., 0.0582, 0.7406, 0.3631],
        ...,
        [0.7590, 0.4177, 0.8811,  ..., 0.8605, 0.3979, 0.3215],
        [0.1261, 0.9663, 0.3203,  ..., 0.7477, 0.8248, 0.2202],
        [0.5180, 0.5028, 0.9692,  ..., 0.7702, 0.6319, 0.4732]])

Tensors placed on CPU and tensors placed on GPU are unavailable for each other:

In [117]:
a = torch.FloatTensor(10000, 10000).uniform_().cpu()
b = torch.FloatTensor(10000, 10000).uniform_().cuda()

In [118]:
a + b

RuntimeError: ignored

Example of working with GPU:

In [ ]:
torch.cuda.is_available()

In [120]:
x = torch.FloatTensor(5, 5, 5).uniform_()
print(x.device)

cpu


In [121]:
# check for CUDA availability (NVIDIA GPU)
if torch.cuda.is_available():
    # get the CUDA device name
    device = torch.device('cuda')          # CUDA-device object
else:
    device = torch.device('cpu')           # cpu-device object

print(device)

cuda


In [126]:
y = torch.ones_like(x, device=device)  # create a tensor on GPU
x = x.to(device)                       # or just `.to("cuda")`

print('x.device:', x.device)
print('y.device:', y.device)

x.device: cuda:0
y.device: cuda:0


In [127]:
z = x + y
print(z, '\n')

print('-'*80, '\n')

# you can set the type with `.to` operation
print(z.to("cpu", torch.double))

tensor([[[1.7403, 1.2417, 1.4201, 1.3442, 1.2671],
         [1.9984, 1.2275, 1.7599, 1.9633, 1.9799],
         [1.7024, 1.3366, 1.9704, 1.5704, 1.1703],
         [1.7936, 1.3927, 1.5141, 1.1881, 1.9071],
         [1.6885, 1.5005, 1.0664, 1.8442, 1.8121]],

        [[1.9351, 1.1392, 1.3859, 1.0911, 1.9168],
         [1.8508, 1.6533, 1.8449, 1.7423, 1.0060],
         [1.3009, 1.7897, 1.4527, 1.1419, 1.6502],
         [1.8964, 1.4958, 1.1332, 1.9201, 1.5266],
         [1.7882, 1.1550, 1.5477, 1.1924, 1.5345]],

        [[1.4955, 1.8743, 1.3370, 1.2139, 1.4850],
         [1.5156, 1.7157, 1.5255, 1.6651, 1.0726],
         [1.2138, 1.5878, 1.0240, 1.5692, 1.6393],
         [1.6525, 1.4932, 1.4209, 1.0356, 1.6063],
         [1.6189, 1.9419, 1.3284, 1.2488, 1.8189]],

        [[1.4922, 1.0660, 1.8325, 1.8700, 1.2364],
         [1.1431, 1.3633, 1.4149, 1.7642, 1.8434],
         [1.8475, 1.0281, 1.0569, 1.4005, 1.0010],
         [1.0243, 1.0695, 1.8314, 1.3718, 1.2155],
         [1.0985, 1.3058,

<h3 style="text-align: center;">Autograd<b></b></h3>

The autograd package provides automatic differentiation for all operations on Tensors. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.

Importing the `Variable()` class:

In [ ]:
from torch.autograd import Variable

Now we will convert `torch.Tensor()` into `torch.Variable()` and we will get just the same tensor but the possibility to calculate the gradients with respect to this tensor.

If `а` is a tensor wrapped into `Variable()`, then `a.backward()` calculates the gradients with respect to all the tensors on which the tensor `a` depends.

**Note:** If you use `pytorch 0.4.0` version (or newer), then `torch.Tensor` and `torch.Variable()` were merged into `torch.Tensor`, so one doesn't need to use `Variable()` any more. (`torch.Variable()` is deprecated).

The examples:

In [128]:
dtype = torch.float
device = torch.device("cuda:0") # Uncomment this to run on GPU

In [ ]:
print(dtype)
print(device)

In [130]:
# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 3, 3, 10

# Create random Tensors to hold input and outputs.
# Setting requires_grad=False indicates that we do not need to compute gradients
# with respect to these Tensors during the backward pass.
x = torch.rand(N, D_in, device=device, dtype=dtype)  # requires_grad=False - by default
y = torch.rand(N, D_out, device=device, dtype=dtype)

# Create random Tensors for weights.
# Setting requires_grad=True indicates that we want to compute gradients with
# respect to these Tensors during the backward pass.
w1 = torch.rand(D_in, H, device=device, dtype=dtype, requires_grad=True)
w2 = torch.rand(H, D_out, device=device, dtype=dtype, requires_grad=True)

y_pred = (x @ w1).clamp(min=0).mm(w2)

loss = (y_pred - y).pow(2).sum()
# calculate the gradients
loss.backward()

In [131]:
print( (y_pred - y).pow(2).sum() )

tensor(720.1266, device='cuda:0', grad_fn=<SumBackward0>)


In [132]:
w1.grad

tensor([[436.7381, 262.5804, 280.8230],
        [474.6253, 285.6278, 303.3613],
        [455.5574, 271.6789, 293.3632]], device='cuda:0')

In [133]:
w2.grad

tensor([[111.6883, 141.9324, 207.5062, 150.7994,  60.2904, 238.9867, 155.1251,
         125.1274, 223.1851,  80.7552],
        [ 85.2258, 108.2235, 157.8692, 115.0474,  46.1179, 181.8002, 118.2492,
          95.5397, 170.1691,  61.6210],
        [ 53.4979,  67.7759,  99.6563,  72.2497,  28.7488, 114.3672,  73.8424,
          59.8304, 106.7556,  38.7885]], device='cuda:0')

In [136]:
# no grad for y since we do not optimize towards it
print(y.grad)

None


In [137]:
# no grad for loss
print(loss.grad)

None


/usr/local/lib/python3.6/dist-packages/torch/tensor.py:746: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  warnings.warn("The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad "


**NOTE:** the gradients are placed into the `.grad` field of tensors (variables) on which gradients were calculated. Gradients *are not placed* in the variable `loss` here!

Here is how to get `torch.Tensor()` from the `Variable()` (`.data` field):

In [139]:
w1

tensor([[0.8754, 0.7377, 0.4623],
        [0.8403, 0.6753, 0.2748],
        [0.6198, 0.3681, 0.3877]], device='cuda:0', requires_grad=True)

In [140]:
w1.data

tensor([[0.8754, 0.7377, 0.4623],
        [0.8403, 0.6753, 0.2748],
        [0.6198, 0.3681, 0.3877]], device='cuda:0')

<h3 style="text-align: center;">Further reading:<b></b></h3>

*1). Official PyTorch tutorials: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py*

*2). arXiv article about the deep learning frameworks comparison: https://arxiv.org/pdf/1511.06435.pdf*

*3). Useful repo with different tutorials: https://github.com/yunjey/pytorch-tutorial*

*4). Facebook AI Research (main contributor of PyTorch) website: https://facebook.ai/developers/tools*